# Generated by Django 4.1.7 on 2023-03-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject_MARK', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AlterField(
            model_name='customer',
            name='room',
            field=models.IntegerField(),
        ),
    ]
